### PR TITLE
Fix minor typos in chapter 07 and 08

### PR DESCRIPTION
**Pull request by plattfot**
Hi,

First of great book, I finished it a few weeks ago, I got some great suggestions on how I could improve my technical writing and note taking. Thank you for taking the time writing it.

I did find some minor typos when reading so here are the fixes for them.

There was also this sentence in the third paragraph of section 10.5:

> Some cynics suggest that those who can't teach.

It seems to be cut off, or should it be " Some cynics suggest that those can't teach."?

Here is the full paragraph:

> The EWS project is my way of giving back to the Emacs community and also helping me better understand how the software works. Some cynics suggest that those who can't teach. However, teaching any subject is the best way to systematise your knowledge and become better at it.

I did not change anything for that as it could just be me not reading it correctly.

### CODE REVIEW

**Comment by pprevos** [comment]
Hi Fredrik, I am glad that the book was helpful for you.

Thanks for the improvements to the text.

Regards

P:)

**Comment by plattfot** [comment]
Did you mean to close this without merging the changes?

**Comment by pprevos** [comment]
Oops, sorry, that was not the intent.

**Comment by pprevos** [comment]
By the way, the cynics reference in ch. 10 should be: "Some cynics suggest that 'those who can't do, teach'."

I am working on the paperback version with some enhanced content. You can easily roll your own e-book from the future sources.

**Pull request merged**
